name: ${project.artifactId}
main: com.mcmiddleearth.architect.watcher.ArchitectWatcherPlugin
version: ${project.version}
author: Eriol_Eandur
load: STARTUP
depend: [MCME-Architect]
api-version: 1.15

